# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='appearance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Match'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Player'),
        ),
    ]
