# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170907_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ['match', 'player']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together=set([('match', 'player')]),
        ),
    ]
