# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
